baseurl = "http://evup.updevcamp.com"
languageCode = "en-us"
title = "EVUP"
pygmentsstyle = "colorful"

[params]
  defaultDescription = "EVUP is the premier event app for UP Diliman"
  defaultKeywords = "UP, Computer, Science, Events, Event, App, iOS, Android"
  googleAnalytics = "UA-21841224-5"
